### PR TITLE
Bankserver

### PR DESCRIPTION
**Pull request by InyangUkpong**
- connected to MongoDB Server
- created APIs: 

1. Fetch All Accounts
2. Create Account
3. Fetch Single Account
4. Delete Account
5. Update Account
6. Fetch All Transactions for an Account
7. Daily Withdrawal Limit
8. Withdrawal
9. Deposit

Project was Dockerized

### CODE REVIEW

**Comment by joshuaunity** [comment]
Hi there, thank you for the submission! However, I would like to request some cleanup in your repository. There are a couple of unwanted files that should be ignored in your .gitignore. Additionally, while the images you added are nice, could you please remove them? They're causing the repository to load slower in the browser. Thanks for your cooperation!

**Comment by InyangUkpong** [comment]
Okay Sir, Please which files would you like me to add to my .gitignore

**Comment by joshuaunity** [comment]
> Okay Sir, Please which files would you like me to add to my .gitignore

.DS_STORE for example and any other file that has nothing to do with the assignment

**Comment by joshuaunity** [comment]
Good morning, I tried running the project and i got an error, try running it on your end especially with docker there is an error.

**Comment by InyangUkpong** [comment]
Good Afternoon Sir, I don't see any error on mines. Or is there something
specific about the docker i need to do?

**Comment by InyangUkpong** [comment]
I have deleted the .DS_Store file. hope this works

**Comment by InyangUkpong** [comment]
> Good morning, I tried running the project and i got an error, try running it on your end especially with docker there is an error.

i don't know what the errors

**Comment by InyangUkpong** [comment]
@joshuaunity i have re-dockerized the app again with a 2.1 version i hope this works sir

**Comment by joshuaunity** [comment]
Hi @InyangUkpong i have reviewed this assignment, first I want to commend your diligence and effort in this program, you are one of the best students and I want to say WELL DONE.

For this assignment, there are a couple of things that need to be worked on, first eh docker issue isn't coming up anymore

second is the "createaccount" API should only take the necessary things and in this case that is first and last name, email and password/pin. every other things like account number and more will be done by you under the hood. Take for example If you went to a bank to open an account, there is no option for you as the customer to type in your own custom account number, that is generated by the system.

The deposit API should take in an extra value which will be password/pin as that extra security is needed in a system like this, the ID you placed in the URL is not needed for withdrawal the password/pin should also be requested cause if you think about it that's how your normal bank app works. Also another note.

The fetch all transaction API doesn't sem to be working

**Comment by InyangUkpong** [comment]
> Hi @InyangUkpong i have reviewed this assignment, first I want to commend your diligence and effort in this program, you are one of the best students and I want to say WELL DONE.
> 
> For this assignment, there are a couple of things that need to be worked on, first eh docker issue isn't coming up anymore
> 
> second is the "createaccount" API should only take the necessary things and in this case that is first and last name, email and password/pin. every other things like account number and more will be done by you under the hood. Take for example If you went to a bank to open an account, there is no option for you as the customer to type in your own custom account number, that is generated by the system.
> 
> The deposit API should take in an extra value which will be password/pin as that extra security is needed in a system like this, the ID you placed in the URL is not needed for withdrawal the password/pin should also be requested cause if you think about it that's how your normal bank app works. Also another note.
> 
> The fetch all transaction API doesn't sem to be working

THANK YOU SO MUCH FOR THE FEEDBACK SIR. I"ll try and rectify the issues.

**Comment by InyangUkpong** [comment]
I have done the mentioned corrections sir @joshuaunity 
please kindly take a look at it

**Comment by joshuaunity** [comment]
> I have made the mentioned corrections sir @joshuaunity please kindly take a look at it

Ok, let me check it out now.

**Comment by joshuaunity** [comment]
Hi @InyangUkpong well done on this, nice work the ocker works fine now👍🏾. Below are the things I found out in my review.

1. I can create multiple accounts with the same details
2. Fetch transactions does not return a list of transactions, it just returns the account details
3. a user shouldn't be able to decide his/her account number the system should generate that, the same as the withdrawal limit
4. one shouldn't be able to directly update the withdrawal limit or the account number
5. daily withdrawal limit works. BUT, will it reset the next day?

**Comment by InyangUkpong** [comment]
@joshuaunity Greetings Sir, i have made the corrections as listed in the email. Best regards.

**Comment by joshuaunity** [comment]
> @joshuaunity Greetings Sir, i have made the corrections as listed in the email. Best regards.

Great, currently reviewing

**Comment by joshuaunity** [comment]
Well done, @InyangUkpong! You have officially completed this assignment, and I want to commend your zealousness throughout this program. I will go ahead and merge your work, but here are a few improvements you can make:

Error responses can be cleaner.
The transactions API returns the transactions correctly, but it should return the array directly rather than as a key-value pair where the value is the array.
Your code could be better organized and cleaned up. There are many comments, and a few things are not properly placed. As a software engineer, it is important to write code that can be easily understood and maintained by other engineers, so take some time to develop this skill.
Again, well done on your assignment! Although today is my last class, I will still be available for contact for a while.

**Comment by InyangUkpong** [comment]
@joshuaunity Thanks for the review sir, i'll work on cleaning up my code.

**Pull request merged**
